name: deploy-auth

on: 
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - run: cd auth && docker build -t oo23ooo/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ sercets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ sercets.DOCKER_PASSWORD }}
      - run: docker push oo23ooo/auth
